%% Test if matlab function operates correctly

hello_world( ...
    'display_string', 'Hello, world!', ...
    'filename','hello_world.txt', ...
    'in_dir','/test', ...
    'out_dir','/OUTPUT' ...
    );