%% Test if matlab function operates correctly

hello_world( ...
    'display_string', 'Hello, world!', ...
    'filename','hello_world.txt', ...
    'in_dir',[ pwd '/INPUTS'], ...
    'out_dir',[pwd '/OUTPUT'] ...
    );